version: "3.8"

services:
  web:
    build:
        context: .
        dockerfile: ./docker/nginx.dockerfile
    image: julioszeferino/nginx:v1
    restart: always
    volumes:
    - ./logs/server:/var/log/nginx/
    ports:
    - 8080:8080
    environment:
    - NGINX_PORT=80
    networks:
      - api-nw
    depends_on:
      - pgdb
      - api

  pgdb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: faculdade
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminsenha
    networks:
      - api-nw
    volumes:
      - pg-volume:/var/lib/postgresql/data

  api:
    build:
      dockerfile: ./docker/fastapi.dockerfile
      context: .
    restart: always
    image: julioszeferino/fastapi:v1
    container_name: api
    ports:
      - 8000
      # - 8000:8000
    networks:
      - api-nw
    depends_on:
      - pgdb



networks:
  api-nw:
    driver: bridge

volumes:
  pg-volume: